# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-15 09:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mission', '0002_auto_20161015_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finished',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, upload_to='static/images')),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='finishers',
        ),
        migrations.AddField(
            model_name='finished',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finished', to='mission.Task'),
        ),
        migrations.AddField(
            model_name='finished',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finished', to=settings.AUTH_USER_MODEL),
        ),
    ]
